"use client";

import { useMemo, useState } from "react";
import { BrandForm, CategoryForm } from "@/components/admin/catalog-forms";

type Category = Parameters<typeof CategoryForm>[0]["categories"][number] & { _count: { products: number; children: number } };
type Brand = NonNullable<Parameters<typeof BrandForm>[0]["initial"]> & { _count: { products: number } };

function Count({ value }: { value: number }) {
  return <span className="text-sm font-medium tabular-nums text-foreground">{value} <span className="text-muted-foreground">{value === 1 ? "product" : "products"}</span></span>;
}

function StatusBadge({ active }: { active: boolean }) {
  return <span className={active ? "catalog-status-active" : "catalog-status-inactive"}>{active ? "Active" : "Inactive"}</span>;
}

export function CategoryManager({ categories }: { categories: Category[] }) {
  const [editing, setEditing] = useState<Category | undefined>();
  const parents = useMemo(() => new Map(categories.map((category) => [category.id, category.name])), [categories]);

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_25rem]"><section aria-label="Category records" className="min-w-0 overflow-hidden rounded-xl border border-[#cfc4b4] bg-card/90 shadow-[0_1px_2px_rgb(63_45_29/.06)]"><div className="flex items-center justify-between border-b border-[#d8cebf] px-4 py-4 sm:px-5"><div><h2 className="font-semibold">Category records</h2><p className="mt-1 text-sm text-muted-foreground">{categories.length} {categories.length === 1 ? "category" : "categories"} in the catalog</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#f7f3ea]/80 text-xs uppercase tracking-[.1em] text-muted-foreground"><tr><th scope="col" className="px-5 py-3 font-bold">Category</th><th scope="col" className="px-4 py-3 font-bold">Slug</th><th scope="col" className="px-4 py-3 font-bold">Products</th><th scope="col" className="px-4 py-3 font-bold">Status</th><th scope="col" className="px-5 py-3 text-right font-bold">Action</th></tr></thead><tbody className="divide-y divide-[#e0d8cc]">{categories.length ? categories.map((category) => <tr className={editing?.id === category.id ? "bg-[#f9e5dd]/60" : "transition-colors hover:bg-[#faf6ee]"} key={category.id}><td className="px-5 py-4"><div className="font-semibold text-foreground">{category.parentId && <span className="mr-1.5 text-xs font-bold text-[#8b5946]">{parents.get(category.parentId)} ›</span>}{category.name}</div>{category.parentId && <div className="mt-1 text-xs text-muted-foreground">Nested category</div>}</td><td className="px-4 py-4 font-mono text-xs text-muted-foreground">{category.slug}</td><td className="px-4 py-4"><Count value={category._count.products}/></td><td className="px-4 py-4"><StatusBadge active={category.isActive}/></td><td className="px-5 py-4 text-right"><button onClick={() => setEditing(category)} aria-label={`Edit category ${category.name}`} className="catalog-secondary-button min-h-9 px-3 text-xs">Edit</button></td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center"><p className="font-semibold">No categories yet</p><p className="mt-1 text-sm text-muted-foreground">Create the first category using the form.</p></td></tr>}</tbody></table></div></section><aside className="xl:sticky xl:top-6 xl:self-start"><CategoryForm key={editing?.id ?? "new"} categories={categories} initial={editing}/>{editing && <button onClick={() => setEditing(undefined)} className="catalog-secondary-button mt-3 w-full">Cancel edit</button>}</aside></div>;
}

export function BrandManager({ brands }: { brands: Brand[] }) {
  const [editing, setEditing] = useState<Brand | undefined>();

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_25rem]"><section aria-label="Brand records" className="min-w-0 overflow-hidden rounded-xl border border-[#cfc4b4] bg-card/90 shadow-[0_1px_2px_rgb(63_45_29/.06)]"><div className="flex items-center justify-between border-b border-[#d8cebf] px-4 py-4 sm:px-5"><div><h2 className="font-semibold">Brand records</h2><p className="mt-1 text-sm text-muted-foreground">{brands.length} {brands.length === 1 ? "brand" : "brands"} available to the catalog</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-[#f7f3ea]/80 text-xs uppercase tracking-[.1em] text-muted-foreground"><tr><th scope="col" className="px-5 py-3 font-bold">Brand</th><th scope="col" className="px-4 py-3 font-bold">Slug</th><th scope="col" className="px-4 py-3 font-bold">Products</th><th scope="col" className="px-4 py-3 font-bold">Status</th><th scope="col" className="px-5 py-3 text-right font-bold">Action</th></tr></thead><tbody className="divide-y divide-[#e0d8cc]">{brands.length ? brands.map((brand) => <tr className={editing?.id === brand.id ? "bg-[#f9e5dd]/60" : "transition-colors hover:bg-[#faf6ee]"} key={brand.id}><td className="px-5 py-4"><div className="font-semibold text-foreground">{brand.name}</div>{brand.logoUrl ? <div className="mt-1 truncate text-xs text-muted-foreground">Logo URL configured</div> : <div className="mt-1 text-xs text-muted-foreground">No logo URL</div>}</td><td className="px-4 py-4 font-mono text-xs text-muted-foreground">{brand.slug}</td><td className="px-4 py-4"><Count value={brand._count.products}/></td><td className="px-4 py-4"><StatusBadge active={brand.isActive}/></td><td className="px-5 py-4 text-right"><button onClick={() => setEditing(brand)} aria-label={`Edit brand ${brand.name}`} className="catalog-secondary-button min-h-9 px-3 text-xs">Edit</button></td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center"><p className="font-semibold">No brands yet</p><p className="mt-1 text-sm text-muted-foreground">Create the first brand using the form.</p></td></tr>}</tbody></table></div></section><aside className="xl:sticky xl:top-6 xl:self-start"><BrandForm key={editing?.id ?? "new"} initial={editing}/>{editing && <button onClick={() => setEditing(undefined)} className="catalog-secondary-button mt-3 w-full">Cancel edit</button>}</aside></div>;
}
