"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Box, Trash2, Upload } from "lucide-react";
import { ProductModelViewer } from "@/components/store/product-model-viewer";
export type ManagedModel = { id: string; publicUrl: string; originalFilename: string; fileSize: number };
export function ProductModelManager({ productId, productName, model }: { productId?: string; productName: string; model?: ManagedModel | null }) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  if (!productId) return <div className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Create the product first, then optionally upload one GLB model.</div>;
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || busy) return; setBusy(true); setMessage(model ? "Replacing 3D model…" : "Uploading 3D model…"); const body = new FormData(); body.set("model", file); const response = await fetch(`/api/admin/products/${productId}/model`, { method: "POST", body }); const result = await response.json() as { message?: string }; setMessage(response.ok ? (model ? "3D model replaced." : "3D model uploaded.") : result.message || "Unable to upload 3D model."); if (input.current) input.current.value = ""; setBusy(false); if (response.ok) router.refresh(); };
  const remove = async () => { if (busy) return; setBusy(true); const response = await fetch(`/api/admin/products/${productId}/model`, { method: "DELETE" }); const result = await response.json() as { message?: string }; setMessage(result.message || (response.ok ? "3D model removed." : "Unable to remove 3D model.")); setBusy(false); if (response.ok) router.refresh(); };
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><label className="catalog-primary-button cursor-pointer"><Upload className="mr-2 inline size-4"/>{busy ? "Working…" : model ? "Replace GLB" : "Upload GLB"}<input ref={input} className="sr-only" aria-label={model ? "Replace product 3D model" : "Upload product 3D model"} type="file" accept=".glb,model/gltf-binary" disabled={busy} onChange={upload}/></label><span className="text-sm text-muted-foreground">GLB only · smaller than 25 MB</span></div><p role={message ? "status" : undefined} aria-live="polite" className="min-h-5 text-sm text-[#8b5946]">{message}</p>{model ? <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-[#f3eee6] p-3 text-sm"><span><Box className="mr-2 inline size-4"/>{model.originalFilename} · {(model.fileSize / 1024).toFixed(1)} KB</span><button type="button" disabled={busy} className="catalog-secondary-button text-red-700" aria-label="Remove product 3D model" onClick={remove}><Trash2 className="size-4"/> Remove</button></div><ProductModelViewer src={model.publicUrl} productName={productName}/></div> : <div className="rounded-lg bg-[#f3eee6] p-4 text-sm"><strong>No 3D model uploaded.</strong> Product photography remains the default presentation.</div>}</div>;
}
