import { expect, test } from "@playwright/test";
import { hash } from "bcryptjs";
import { unlink } from "fs/promises";
import path from "path";
import { prisma } from "../src/lib/db/prisma";
import { runId } from "./helpers/test-data";

const id = runId(); const slug = `phase5d-model-${id}`; const email = `phase5d-customer-${id}@example.test`; const password = "ModelTest-4A";
function glb(label: string) { const json = JSON.stringify({ asset: { version: "2.0", generator: label }, scene: 0, scenes: [{ nodes: [0] }], nodes: [{}] }); const padded = json.padEnd(Math.ceil(json.length / 4) * 4, " "); const total = 12 + 8 + padded.length; const out = Buffer.alloc(total); out.write("glTF", 0); out.writeUInt32LE(2, 4); out.writeUInt32LE(total, 8); out.writeUInt32LE(padded.length, 12); out.write("JSON", 16); out.write(padded, 20); return out; }
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64"); const assets = new Set<string>();
async function product() { return prisma.product.findUnique({ where: { slug }, include: { model3d: true, images: true, variants: true } }); }
test.describe.configure({ mode: "serial", timeout: 120_000 });
test.afterAll(async () => { const item = await product(); if (item) { if (item.model3d) assets.add(item.model3d.publicUrl); item.images.forEach((image) => assets.add(image.url)); await prisma.cartItem.deleteMany({ where: { variant: { productId: item.id } } }); await prisma.auditLog.deleteMany({ where: { entityId: item.id } }); await prisma.product.delete({ where: { id: item.id } }); } for (const url of assets) { const folder = url.includes("/model/") ? "model" : "product"; if (url.startsWith("/api/media/")) await unlink(path.join(process.cwd(), ".media", folder, path.basename(url))).catch(() => undefined); } await prisma.user.deleteMany({ where: { email } }); await prisma.$disconnect(); });

test("admin uploads, previews, replaces, and removes a lazy storefront GLB", async ({ page }) => {
  const category = await prisma.category.findFirstOrThrow({ where: { isActive: true } }); const brand = await prisma.brand.findFirstOrThrow({ where: { isActive: true } });
  await page.goto("/admin/products/new"); await page.getByLabel("Name").fill(`Phase 5D Model ${id}`); await page.getByLabel("Slug").fill(slug); await page.getByLabel("Status").selectOption("ACTIVE"); await page.getByLabel("Category").selectOption(category.id); await page.getByLabel("Brand").selectOption(brand.id); await page.getByLabel("SKU").fill(`P5D-${id}`); await page.getByLabel("Regular price").fill("72"); await page.getByLabel("Quantity").fill("5"); await page.getByLabel("Low-stock threshold").fill("1"); await page.getByRole("button", { name: "Create product" }).click(); await page.waitForURL(/\/admin\/products\/.+/);
  await page.getByLabel("Upload product image").setInputFiles({ name: "product.png", mimeType: "image/png", buffer: png }); await expect(page.getByText("Image uploaded.")).toBeVisible();
  await page.getByLabel("Upload product 3D model").setInputFiles({ name: "model.glb", mimeType: "model/gltf-binary", buffer: glb("first") }); await expect(page.getByText("3D model uploaded.")).toBeVisible();
  await expect.poll(async () => (await product())?.model3d?.originalFilename).toBe("model.glb"); let item = await product(); assets.add(item!.model3d!.publicUrl); const firstUrl = item!.model3d!.publicUrl;
  for (const width of [375,768,1024,1440]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await expect(page.getByLabel("Replace product 3D model")).toBeAttached(); await expect(page.getByTestId("product-model-viewer")).toBeAttached(); }
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: "test-results/phase5d-admin-model-1440.png", fullPage: true }); await page.setViewportSize({ width: 375, height: 900 }); await page.screenshot({ path: "test-results/phase5d-admin-model-375.png", fullPage: true });
  const modelRequests: string[] = []; page.on("request", (request) => { if (request.url().includes("/api/media/model/")) modelRequests.push(request.url()); }); await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto(`/products/${slug}`); await expect(page.getByTestId("product-gallery-main")).toBeVisible(); expect(modelRequests).toHaveLength(0); await page.screenshot({ path: "test-results/phase5d-product-images-1440.png", fullPage: true }); await page.setViewportSize({ width: 375, height: 900 }); await page.screenshot({ path: "test-results/phase5d-product-images-375.png", fullPage: true });
  await page.getByRole("button", { name: "View in 3D" }).click(); await expect(page.getByTestId("product-model-viewer")).toBeAttached(); await expect.poll(() => modelRequests.length).toBeGreaterThan(0); await expect(page.getByRole("button", { name: "Reset 3D view" })).toBeVisible(); await page.getByText("Auto-rotate off").click(); await expect(page.getByText("Auto-rotate on")).toBeVisible(); await page.getByRole("button", { name: "Add to cart" }).click();
  for (const width of [375,768,1024,1440]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await expect(page.getByRole("button", { name: "Reset 3D view" })).toBeVisible(); await expect(page.getByRole("button", { name: "Add to cart" })).toBeVisible(); }
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: "test-results/phase5d-product-3d-1440.png", fullPage: true }); await page.setViewportSize({ width: 375, height: 900 }); await page.screenshot({ path: "test-results/phase5d-product-3d-375.png", fullPage: true });
  await page.goto(`/admin/products/${item!.id}`); await page.getByLabel("Replace product 3D model").setInputFiles({ name: "replacement.glb", mimeType: "model/gltf-binary", buffer: glb("replacement") }); await expect(page.getByText("3D model replaced.")).toBeVisible(); item = await product(); expect(item?.model3d?.publicUrl).not.toBe(firstUrl); assets.add(item!.model3d!.publicUrl); await expect.poll(async () => { try { await unlink(path.join(process.cwd(), ".media", "model", path.basename(firstUrl))); return false; } catch { return true; } }).toBe(true); expect(item?.images).toHaveLength(1);
  await page.getByRole("button", { name: "Remove product 3D model" }).click(); await expect(page.getByText("3D model removed.")).toBeVisible(); await expect.poll(async () => (await product())?.model3d).toBeNull(); await page.goto(`/products/${slug}`); await expect(page.getByRole("button", { name: "View in 3D" })).toHaveCount(0); await expect(page.getByRole("button", { name: "Add to cart" })).toBeVisible(); expect((await product())?.images).toHaveLength(1);
});

test("model upload authorization and validation reject unsafe requests", async ({ page, browser }) => {
  const item = await product(); expect(item).toBeTruthy(); const endpoint = `/api/admin/products/${item!.id}/model`;
  const anonymous = await browser.newContext({ storageState: { cookies: [], origins: [] } }); expect((await anonymous.request.post(endpoint, { multipart: { model: { name: "model.glb", mimeType: "model/gltf-binary", buffer: glb("anonymous") } } })).status()).toBe(401); await anonymous.close();
  await prisma.user.create({ data: { email, name: "Phase 5D Customer", role: "CUSTOMER", emailVerifiedAt: new Date(), passwordHash: await hash(password, 10) } }); const customer = await browser.newContext({ storageState: { cookies: [], origins: [] } }); const customerPage = await customer.newPage(); await customerPage.goto("/login"); await customerPage.getByLabel("Email", { exact: true }).fill(email); await customerPage.getByLabel("Password", { exact: true }).fill(password); await customerPage.getByRole("button", { name: "Sign in" }).click(); await customerPage.waitForURL(/\/account/); expect((await customer.request.post(endpoint, { multipart: { model: { name: "model.glb", mimeType: "model/gltf-binary", buffer: glb("customer") } } })).status()).toBe(403); await customer.close();
  expect((await page.request.post(endpoint, { multipart: { model: { name: "model.obj", mimeType: "model/gltf-binary", buffer: glb("wrong") } } })).status()).toBe(400); expect((await page.request.post(endpoint, { multipart: { model: { name: "fake.glb", mimeType: "model/gltf-binary", buffer: Buffer.alloc(12) } } })).status()).toBe(400); expect((await page.request.post(endpoint, { multipart: { model: { name: "huge.glb", mimeType: "model/gltf-binary", buffer: Buffer.alloc(25 * 1024 * 1024) } } })).status()).toBe(400); expect((await product())?.model3d).toBeNull();
  await prisma.product3DModel.create({ data: { productId: item!.id, storageKey: "missing.glb", publicUrl: "/api/media/model/missing.glb", originalFilename: "missing.glb", contentType: "model/gltf-binary", fileSize: 12 } }); await page.goto(`/products/${slug}`); await page.getByRole("button", { name: "View in 3D" }).click(); await expect(page.getByText("3D preview is unavailable. Product images and purchasing remain available.")).toBeVisible(); await expect(page.getByRole("button", { name: "Add to cart" })).toBeVisible(); await page.getByRole("button", { name: "View images" }).click(); await expect(page.getByTestId("product-gallery-main")).toBeVisible(); await prisma.product3DModel.delete({ where: { productId: item!.id } });
});
