import { expect, test } from "@playwright/test";
import { cleanupProductBySlug, countProductsBySlug, disconnectE2EDatabase, findAuditLogsForEntity, findProductBySlug, seededCategoryAndBrand } from "./helpers/db";
import { runId } from "./helpers/test-data";

const id = runId(); const slug = `e2e-product-${id}`; const sku = `e2e-sku-${id}`; const duplicateSkuSlug = `e2e-product-sku-duplicate-${id}`;
test.afterAll(async () => { await cleanupProductBySlug(slug); await cleanupProductBySlug(duplicateSkuSlug); await disconnectE2EDatabase(); });
test("authenticated product create, edit, duplicate safety, and audit smoke", async ({ page }) => {
  test.setTimeout(120_000); const [category, brand] = await seededCategoryAndBrand(); expect(category).toBeTruthy(); expect(brand).toBeTruthy(); if (!category || !brand) throw new Error("Missing seeded category or brand.");
  await page.goto("/admin/products/new"); await expect(page.getByRole("heading", { name: "Create product" })).toBeVisible();
  await page.getByLabel("Name").first().fill(`E2E Product ${id}`); await page.getByLabel("Slug").first().fill(slug); await page.getByLabel("Short description").first().fill("Product smoke short description"); await page.getByRole("textbox", { name: "Description", exact: true }).fill("Product smoke description"); await page.getByLabel("Status").first().selectOption("DRAFT"); await page.getByLabel("Category").first().selectOption(category.id); await page.getByLabel("Brand").first().selectOption(brand.id); await page.getByLabel("Image URL").first().fill("https://example.com/e2e-product.jpg"); await page.getByLabel("Image alt text").first().fill("E2E product image"); await page.getByLabel("SKU").first().fill(sku); await page.getByLabel("Regular price").first().fill("29.99"); await page.getByLabel("Sale price").first().fill("24.99"); await page.getByLabel("Cost price (admin only)").first().fill("12.50"); await page.getByLabel("Quantity").first().fill("25"); await page.getByLabel("Low-stock threshold").first().fill("5"); await page.getByLabel("SEO title").first().fill("E2E initial SEO"); await page.getByRole("button", { name: "Create product" }).click(); await expect(page.getByRole("status")).toHaveText("Product created."); await page.waitForURL(/\/admin\/products\/(?!new$)[^/]+$/, { timeout: 15_000 });
  const created = await findProductBySlug(slug); expect(created).toBeTruthy(); expect(created?.status).toBe("DRAFT"); expect(created?.images).toHaveLength(1); const variantBefore = created?.variants[0]; expect(variantBefore?.sku).toBe(sku); expect(variantBefore?.price?.toString()).toBe("29.99"); expect(variantBefore?.inventory?.quantity).toBe(25); const inventoryId = variantBefore?.inventory?.id; expect(inventoryId).toBeTruthy();
  await page.goto(`/admin/products?q=${slug}`); await expect(page.getByText(`E2E Product ${id}`).first()).toBeVisible(); await expect(page.getByText(sku).first()).toBeVisible(); await expect(page.getByRole("cell", { name: "DRAFT" }).first()).toBeVisible();
  await page.getByRole("link", { name: "Edit" }).click(); await page.getByLabel("Name").first().fill(`E2E Product Edited ${id}`); await page.getByLabel("Regular price").first().fill("35.50"); await page.getByLabel("Quantity").first().fill("7"); await page.getByLabel("SEO title").first().fill("E2E edited SEO"); await page.getByRole("button", { name: "Save product" }).click(); await expect(page.getByRole("status")).toHaveText("Product updated."); await page.reload();
  const edited = await findProductBySlug(slug); expect(edited?.name).toBe(`E2E Product Edited ${id}`); expect(edited?.seoTitle).toBe("E2E edited SEO"); expect(edited?.variants[0]?.id).toBe(variantBefore?.id); expect(edited?.variants[0]?.sku).toBe(sku); expect(Number(edited?.variants[0]?.price?.toString())).toBe(35.5); expect(edited?.variants[0]?.inventory?.quantity).toBe(7); expect(edited?.variants[0]?.inventory?.id).toBe(inventoryId);
  const logs = await findAuditLogsForEntity("Product", edited!.id); expect(logs.map(log => log.action)).toContain("PRODUCT_CREATED"); expect(logs.map(log => log.action)).toContain("PRODUCT_UPDATED"); expect(logs.map(log => log.action)).toContain("INVENTORY_UPDATED");
  await page.goto("/admin/products/new"); await page.getByLabel("Name").first().fill(`Duplicate slug ${id}`); await page.getByLabel("Slug").first().fill(slug); await page.getByLabel("Category").first().selectOption(category.id); await page.getByLabel("Brand").first().selectOption(brand.id); await page.getByLabel("SKU").first().fill(`e2e-duplicate-slug-sku-${id}`); await page.getByLabel("Regular price").first().fill("10"); await page.getByLabel("Quantity").first().fill("1"); await page.getByLabel("Low-stock threshold").first().fill("0"); await page.getByRole("button", { name: "Create product" }).click(); await expect(page.getByRole("status")).toHaveText("This product slug is already in use."); expect(await countProductsBySlug(slug)).toBe(1);
  await page.goto("/admin/products/new"); await page.getByLabel("Name").first().fill(`Duplicate SKU ${id}`); await page.getByLabel("Slug").first().fill(duplicateSkuSlug); await page.getByLabel("Category").first().selectOption(category.id); await page.getByLabel("Brand").first().selectOption(brand.id); await page.getByLabel("SKU").first().fill(sku); await page.getByLabel("Regular price").first().fill("10"); await page.getByLabel("Quantity").first().fill("1"); await page.getByLabel("Low-stock threshold").first().fill("0"); await page.getByRole("button", { name: "Create product" }).click(); await expect(page.getByRole("status")).toHaveText("This SKU is already in use."); expect(await countProductsBySlug(duplicateSkuSlug)).toBe(0);
});
