import Image from "next/image"; import Link from "next/link"; import { PackageOpen } from "lucide-react"; import { getAdminProducts, getProductFormOptions } from "@/features/products/admin-queries";
export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) { const params = await searchParams; const [data, options] = await Promise.all([getAdminProducts({ q: params.q, status: params.status, category: params.category, brand: params.brand, page: Number(params.page) || 1 }), getProductFormOptions()]); const query = (page: number) => new URLSearchParams({ ...Object.fromEntries(Object.entries(params).filter(([,v]) => v)), page: String(page) }).toString(); return <main className="admin-paper min-h-[calc(100vh-4rem)] px-4 py-7 sm:px-7 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8b5946]">Catalog products</p><h1 className="mt-2 text-3xl font-semibold">Products</h1><p className="mt-2 text-sm text-muted-foreground">{data.total} products in the catalog.</p></div><Link href="/admin/products/new" className="catalog-primary-button">Create product</Link></div><form className="mt-6 grid gap-3 rounded-xl border border-[#d8d0c3] bg-white/70 p-4 sm:grid-cols-4"><input className="catalog-field" name="q" defaultValue={params.q} placeholder="Search name, slug, SKU" aria-label="Search products"/><select className="catalog-field" name="status" defaultValue={params.status}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select><select className="catalog-field" name="category" defaultValue={params.category}><option value="">All categories</option>{options.categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><select className="catalog-field" name="brand" defaultValue={params.brand}><option value="">All brands</option>{options.brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="catalog-secondary-button sm:col-span-4 sm:w-fit">Apply filters</button></form><div className="mt-6 overflow-x-auto rounded-xl border border-[#d8d0c3] bg-white/75"><table className="w-full min-w-[920px] text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-muted-foreground"><th className="p-4">Product</th><th>SKU</th><th>Category</th><th>Brand</th><th>Price</th><th>Inventory</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{data.products.map(product=>{ 
  let minPrice = Infinity; let maxPrice = -Infinity; let totalQty = 0; let totalReserved = 0; let outOfStock = 0; let lowStock = 0;
  if (product.variants.length > 0) {
    product.variants.forEach(v => { 
      const p = Number(v.salePrice ?? v.price ?? product.basePrice); 
      if (p < minPrice) minPrice = p; if (p > maxPrice) maxPrice = p;
      const q = v.inventory?.quantity ?? 0;
      const r = v.inventory?.reservedQuantity ?? 0;
      totalQty += q; totalReserved += r;
      if (q === 0) outOfStock++;
      else if (q <= (v.inventory?.reorderPoint ?? 0)) lowStock++;
    });
  } else { minPrice = maxPrice = Number(product.basePrice); }
  const isRange = minPrice !== maxPrice && minPrice !== Infinity;
  const priceDisplay = isRange ? `${minPrice.toFixed(2)} – ${maxPrice.toFixed(2)}` : (minPrice !== Infinity ? minPrice.toFixed(2) : String(product.basePrice));
  const totalAvailable = totalQty - totalReserved;
  const state = outOfStock === product.variants.length ? "Out of stock" : (lowStock > 0 || outOfStock > 0 ? "Mixed / Low" : "In stock");

  return <tr key={product.id} className="border-b last:border-0"><td className="p-4 font-medium"><span className="mr-3 inline-flex size-10 items-center justify-center overflow-hidden rounded border bg-[#e7e1d6] align-middle">{product.images[0] ? <Image src={product.images[0].url} alt={product.images[0].altText ?? ""} width={40} height={40} className="size-10 object-cover"/> : <PackageOpen className="size-4 text-[#8b5946]" aria-label="No product image"/>}</span>{product.name}</td><td>{product.variants[0]?.sku ?? product.sku}</td><td>{product.category.name}</td><td>{product.brand?.name ?? "—"}</td><td>{priceDisplay}</td><td>{state} ({totalAvailable} total)</td><td>{product.status}</td><td>{product.updatedAt.toLocaleDateString()}</td><td><Link className="catalog-secondary-button" href={`/admin/products/${product.id}`}>Edit</Link></td></tr>})}</tbody></table>{data.products.length===0&&<p className="p-8 text-center text-sm text-muted-foreground">No products match these filters.</p>}</div><div className="mt-5 flex items-center justify-between text-sm"><span>Page {data.page} of {data.pages}</span><div className="flex gap-2">{data.page>1&&<Link className="catalog-secondary-button" href={`?${query(data.page-1)}`}>Previous</Link>}{data.page<data.pages&&<Link className="catalog-secondary-button" href={`?${query(data.page+1)}`}>Next</Link>}</div></div></div></main>; }
