import { CircleAlert } from "lucide-react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { getAdminDashboard } from "@/features/admin/dashboard";
import { requireCatalogManager } from "@/lib/auth/session";
import { formatCurrency } from "@/lib/utils";

export default async function AdminHome() {
  await requireCatalogManager();
  const dashboard = await getAdminDashboard();
  const metrics = [["Orders", dashboard.totalOrders], ["Pending orders", dashboard.pendingOrders], ["Customers", dashboard.customers], ["Active products", dashboard.activeProducts]] as const;
  return <main className="p-4 sm:p-7"><p className="text-sm text-muted-foreground">Live operations overview</p><h1 className="mt-1 text-2xl font-semibold">Dashboard</h1><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, amount]) => <Card key={label}><CardContent><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{amount.toLocaleString()}</p></CardContent></Card>)}</section><section className="mt-6 grid gap-4 sm:grid-cols-2"><Card><CardContent><p className="flex items-center gap-2 text-sm text-muted-foreground"><CircleAlert className="size-4 text-amber-600"/>Low stock variants</p><p className="mt-2 text-2xl font-semibold">{dashboard.lowStock}</p></CardContent></Card><Card><CardContent><p className="flex items-center gap-2 text-sm text-muted-foreground"><CircleAlert className="size-4 text-destructive"/>Out of stock variants</p><p className="mt-2 text-2xl font-semibold">{dashboard.outOfStock}</p></CardContent></Card></section><Card className="mt-6 overflow-hidden"><CardContent className="p-0"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Recent orders</h2><p className="text-sm text-muted-foreground">Latest customer activity</p></div><Link href="/admin/orders" className="catalog-secondary-button">View all orders</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-y bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Order</th><th className="px-5 py-3 font-medium">Customer</th><th className="px-5 py-3 font-medium">Amount</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{dashboard.recentOrders.length ? dashboard.recentOrders.map((order) => <tr className="border-b last:border-0" key={order.id}><td className="px-5 py-4"><Link className="font-medium text-[#8b5946] hover:underline" href={`/admin/orders/${order.id}`}>#{order.orderNumber}</Link></td><td className="px-5 py-4">{order.email}</td><td className="px-5 py-4">{formatCurrency(Number(order.grandTotal))}</td><td className="px-5 py-4"><span className="rounded-full bg-muted px-2 py-1 text-xs font-medium">{order.status}</span></td></tr>) : <tr><td className="px-5 py-8 text-muted-foreground" colSpan={4}>No orders yet.</td></tr>}</tbody></table></div></CardContent></Card></main>;
}
