import { prisma } from "@/lib/db/prisma";
import { requireAdminUser } from "@/lib/auth/session";
import { setReviewPublication } from "@/features/reviews/actions";

export default async function AdminReviewsPage() {
  await requireAdminUser();
  const reviews = await prisma.review.findMany({ orderBy: { createdAt: "desc" }, select: { id: true, rating: true, title: true, body: true, isPublished: true, createdAt: true, product: { select: { name: true } }, user: { select: { name: true } } } });
  return <main className="p-4 sm:p-7"><p className="text-sm text-muted-foreground">Admin / Reviews</p><h1 className="mt-1 text-2xl font-semibold">Reviews</h1><div className="mt-6 overflow-x-auto rounded-lg border bg-card"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-4">Product</th><th className="p-4">Customer</th><th className="p-4">Rating</th><th className="p-4">Review</th><th className="p-4">Status</th><th className="p-4">Date</th><th className="p-4">Actions</th></tr></thead><tbody>{reviews.length ? reviews.map((review) => <tr key={review.id} className="border-b last:border-0"><td className="p-4 font-medium">{review.product.name}</td><td className="p-4">{review.user.name ?? "Customer"}</td><td className="p-4">{review.rating}/5</td><td className="max-w-xs p-4"><p className="font-medium">{review.title}</p><p className="truncate text-muted-foreground">{review.body}</p></td><td className="p-4">{review.isPublished ? "Approved" : "Hidden"}</td><td className="p-4">{review.createdAt.toLocaleDateString()}</td><td className="p-4"><form action={setReviewPublication.bind(null, review.id, !review.isPublished)}><button className="catalog-secondary-button" aria-label={`${review.isPublished ? "Hide" : "Approve"} review for ${review.product.name}`}>{review.isPublished ? "Hide" : "Approve"}</button></form></td></tr>) : <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No reviews yet.</td></tr>}</tbody></table></div></main>;
}
